package com.example.thuchanh1

import android.app.Activity
import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Scaffold
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.tooling.preview.Preview
import androidx.core.os.bundleOf
import com.example.thuchanh1.ui.theme.Thuchanh1Theme
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.analytics.FirebaseAnalytics
import com.google.firebase.analytics.ktx.analytics
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.auth.ktx.auth
import com.google.firebase.ktx.Firebase

class MainActivity : ComponentActivity() {
    // Use Firebase KTX property to avoid deprecated API
    private val analytics: FirebaseAnalytics by lazy { Firebase.analytics }
    private val auth: FirebaseAuth by lazy { Firebase.auth }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Use explicit Bundle to avoid deprecated lambda-based API
        val params = bundleOf("version" to "1.0")
        analytics.logEvent("app_started", params)

        // Determine initial auth state from current Firebase user (if any)
        val initialAuthState: AuthState = auth.currentUser?.let { user ->
            AuthState.Success(user.email ?: "Unknown")
        } ?: AuthState.Idle

        enableEdgeToEdge()
        setContent {
            Thuchanh1Theme {
                Scaffold(modifier = Modifier.fillMaxSize()) { innerPadding ->
                    val context = LocalContext.current

                    // Compose-managed auth state shown in MainScreen
                    var authState by remember { mutableStateOf<AuthState>(initialAuthState) }

                    // Read default web client id from resources and validate it
                    val defaultWebClientId = try {
                        context.getString(R.string.default_web_client_id)
                    } catch (e: Exception) {
                        ""
                    }
                    val configValid = defaultWebClientId.isNotBlank()
                            && !defaultWebClientId.contains("YOUR_WEB_CLIENT_ID")
                            && defaultWebClientId.endsWith(".apps.googleusercontent.com")

                    // If config invalid and no user signed in, show helpful error state
                    if (!configValid && (authState is AuthState.Idle)) {
                        authState = AuthState.Error(
                            "App not configured",
                            "Firebase Google Sign-In is not configured.\n1) Add a Web OAuth client ID (or re-download google-services.json).\n2) Add your app's SHA-1 in Firebase console.\n3) Enable Google sign-in in Firebase Authentication."
                        )
                    }

                    // Build GoogleSignInClient with web client id generated by google-services (may be placeholder)
                    val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                        .requestIdToken(defaultWebClientId)
                        .requestEmail()
                        .build()

                    val googleSignInClient = GoogleSignIn.getClient(context, gso)

                    // Activity result launcher for Google SignIn
                    val launcher = rememberLauncherForActivityResult(
                        ActivityResultContracts.StartActivityForResult()
                    ) { result ->
                        if (result.resultCode == Activity.RESULT_OK && result.data != null) {
                            val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
                            try {
                                val account = task.getResult(ApiException::class.java)
                                val idToken = account?.idToken
                                if (idToken == null) {
                                    authState = AuthState.Error("Google Sign-In Failed", "No ID token retrieved")
                                    return@rememberLauncherForActivityResult
                                }

                                // Exchange Google ID token for Firebase credential
                                val credential = GoogleAuthProvider.getCredential(idToken, null)
                                auth.signInWithCredential(credential)
                                    .addOnCompleteListener(this@MainActivity) { authResult ->
                                        if (authResult.isSuccessful) {
                                            val user = auth.currentUser
                                            authState = AuthState.Success(user?.email ?: "Unknown")
                                        } else {
                                            authState = AuthState.Error("Authentication Failed", authResult.exception?.localizedMessage ?: "Unknown error")
                                        }
                                    }

                            } catch (e: ApiException) {
                                Log.e("MainActivity", "Google sign-in failed", e)
                                authState = AuthState.Error("Google Sign-In Failed", e.localizedMessage ?: "Unknown error")
                            }
                        } else {
                            // User cancelled or no data
                            authState = AuthState.Error("Google Sign-In Failed", "User canceled the Google sign-in process.")
                        }
                    }

                    MainScreen(
                        modifier = Modifier.padding(innerPadding),
                        authState = authState,
                        configValid = configValid,
                        onLoginClick = {
                            // If configuration invalid, don't launch sign-in; show guidance
                            if (!configValid) {
                                authState = AuthState.Error(
                                    "Not configured",
                                    "Please configure Firebase Google Sign-In: add Web client ID, add SHA-1, enable Google provider, then re-download google-services.json."
                                )
                                return@MainScreen
                            }

                            // set loading state and launch Google sign-in
                            authState = AuthState.Loading
                            val signInIntent = googleSignInClient.signInIntent
                            launcher.launch(signInIntent)
                        }
                    )
                }
            }
        }
    }
}

@Preview(showBackground = true)
@Composable
fun AppPreview() {
    Thuchanh1Theme {
        MainScreen()
    }
}